# -*- coding: utf-8 -*-
"""pfct_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBGfYNdfmPrZn6x2apSF-ryVEeYBjDeS
"""

num = input()
fear_list = list(map(int, input().split()))
fear_list.sort()

g_count, group_size= 0, 0
for fear in fear_list :
  group_size += 1
  if fear <= group_size:
    g_count += 1
    group_size = 0

print(g_count)